### ISSUE TITLE
why my sprite can't move?

### ISSUE THREAD

**Issue by gdbiomax** [kidscancode/gamedev#2]
I used my code and source code to test the movement, but it looks like 
self.game.dt from clock.tick doesn't work for me. 

self.x += self.vx * self.game.dt
self.y += self.vy * self.game.dt

**Comment by cbscribe** [comment]
Are you using Python 2.7?  If so, you need to slightly change your dt calculation from:

dt = clock.tick(FPS) / 1000

to 

dt = clock.tick(FPS) / 1000.0

This is due to the different ways that Python 2 and Python 3 deal with integer vs. real division.

**Comment by gdbiomax** [comment]
Thanks, it's working now!
